[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "atlasopenmagic"
version = "1.6.0"
description = "A utility package for retrieving ATLAS open data URLs and metadata."
authors = [
    { name="ATLAS Collaboration", email="atlas-outreach-opendata-support@cern.ch" }
]
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
keywords = ["ATLAS", "Open Data", "Utilities"]
classifiers = [
    "Development Status :: 5 - Production/Stable",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",

    "Operating System :: OS Independent",

    "Natural Language :: English",

    "License :: OSI Approved",
    "License :: OSI Approved :: Apache Software License",

    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",

    "Topic :: Documentation",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Utilities",

    "Typing :: Typed",
]
dependencies = [
    "requests",
    "pyyaml"
]

[project.urls]
Homepage = "https://opendata.atlas.cern/"
Repository = "https://github.com/atlas-outreach-data-tools/atlasopenmagic"
Documentation = "https://opendata.atlas.cern/docs/atlasopenmagic"

[project.optional-dependencies]
dev = [
    "pylint",
    "pytest",
    "pytest-cov",
    "pre-commit"
]

[tool.black]
line-length = 112
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 112

[tool.ruff]
line-length = 112
target-version = "py38"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = []

[tool.pydocstyle]
convention = "google"
