name: Install dependencies and build

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/atlasopenmagic

    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v5

    - name: Build a sdist and wheel
      run: |
        set -eux

        uvx --from build pyproject-build

    - name: Validate package structure with twine
      run: uvx twine check --strict dist/*

    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
