name: Install dependencies and build

on:
    pull_request:
      branches: [ "main" ]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Package the files
      run: |
        set -eux

        pip install build
        python -m build --sdist